"""direct sales entry, fuel type entry mode

Adds DirectSale (see models.py) - the tank-keyed, total-liters alternative
to nozzle meter readings (Sale) - and the two FuelType columns that decide
per fuel type whether it's tracked that way: entry_mode ("meter" | "direct")
and direct_entry_combined (only consulted in direct mode on a multi-tank
fuel type - see FuelType's docstring).

Revision ID: 4ee56b5e942d
Revises: ce5be2e3dfbf
Create Date: 2026-08-16 11:52:06.790312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ee56b5e942d'
down_revision = 'ce5be2e3dfbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('direct_sale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tank_id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('liters', sa.Float(), nullable=False),
    sa.Column('price_per_liter', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.Column('pump_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pump_id'], ['pump.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shift.id'], ),
    sa.ForeignKeyConstraint(['tank_id'], ['tank.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tank_id', 'entry_date', 'shift_id', name='uq_directsale_tank_date_shift')
    )
    with op.batch_alter_table('direct_sale', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_direct_sale_pump_id'), ['pump_id'], unique=False)

    with op.batch_alter_table('fuel_type', schema=None) as batch_op:
        # server_default is required on both (autogenerate omits it) - every
        # fuel type that already exists on a populated database has no
        # value yet for these two new NOT NULL columns, so without a
        # default the ALTER fails outright on Postgres, and on SQLite's
        # batch-rebuild every existing row would come back NULL instead of
        # the intended default. "meter" is exactly correct for every fuel
        # type that predates this feature (they were all tracked via
        # nozzle readings, the only mode that existed before now) - not a
        # placeholder guess. False is correct for the same reason
        # (direct_entry_combined only ever matters once entry_mode is
        # "direct", which no pre-existing fuel type is yet). Both values
        # are also each column's permanent application-level default for
        # any future row that omits them (see FuelType in models.py).
        batch_op.add_column(sa.Column('entry_mode', sa.String(length=10), nullable=False, server_default='meter'))
        batch_op.add_column(sa.Column('direct_entry_combined', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_type', schema=None) as batch_op:
        batch_op.drop_column('direct_entry_combined')
        batch_op.drop_column('entry_mode')

    with op.batch_alter_table('direct_sale', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_direct_sale_pump_id'))

    op.drop_table('direct_sale')
    # ### end Alembic commands ###
