"""owner drawing kind, tank starting stock cost

Revision ID: 73feef9be953
Revises: 7864fe7cefce
Create Date: 2026-08-09 16:09:19.738002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73feef9be953'
down_revision = '7864fe7cefce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_loan', schema=None) as batch_op:
        # server_default is required here (autogenerate omits it) - every
        # existing row on a populated table has no value for a nullable=False
        # column being added, so without a default the ALTER fails outright
        # on Postgres, and on SQLite's batch-rebuild every existing row's
        # kind would come back NULL instead of the intended "loan". Every
        # row that predates this column really was a loan/advance (owner
        # drawing is a brand-new kind introduced alongside this column), so
        # backfilling them all to "loan" is exactly correct, not a guess -
        # no separate data migration loop is needed on top of the default.
        # Left in place afterward since "loan" is also the column's
        # permanent application-level default for any future row that
        # omits it (see EmployeeLoan.kind in models.py).
        batch_op.add_column(sa.Column('kind', sa.String(length=10), nullable=False, server_default='loan'))

    with op.batch_alter_table('tank', schema=None) as batch_op:
        # No default needed - NULL is the deliberate, permanent meaning for
        # every tank that predates this column ("historical cost basis
        # unknown" - see Tank.starting_stock_cost_per_liter in models.py),
        # not a placeholder waiting to be backfilled.
        batch_op.add_column(sa.Column('starting_stock_cost_per_liter', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tank', schema=None) as batch_op:
        batch_op.drop_column('starting_stock_cost_per_liter')

    with op.batch_alter_table('employee_loan', schema=None) as batch_op:
        batch_op.drop_column('kind')

    # ### end Alembic commands ###
