"""nozzle testing entries

Revision ID: 7864fe7cefce
Revises: 8f101d39a8c3
Create Date: 2026-08-05 16:54:10.338893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7864fe7cefce'
down_revision = '8f101d39a8c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nozzle_testing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nozzle_id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('liters', sa.Float(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['nozzle_id'], ['nozzle.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shift.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Data backfill: NozzleTesting is now the source of truth that
    # Sale.testing_liters mirrors (see both models' docstrings), so every
    # existing Sale.testing_liters value needs a matching NozzleTesting
    # row - otherwise it's an orphan, and the next time that reading is
    # re-saved, sync_sale_testing() would find nothing recorded for that
    # slot and silently zero the testing back out. Raw SQLAlchemy Core
    # (not the ORM models) is deliberate: a data migration has to keep
    # working exactly as written against the schema as it stood at this
    # revision, regardless of how the ORM models evolve afterward.
    bind = op.get_bind()
    sale_rows = bind.execute(
        sa.text(
            "SELECT nozzle_id, shift_id, entry_date, testing_liters, user_id, recorded_at "
            "FROM sale WHERE testing_liters > 0"
        )
    ).fetchall()
    insert_stmt = sa.text(
        "INSERT INTO nozzle_testing "
        "(nozzle_id, shift_id, entry_date, liters, note, user_id, recorded_at) "
        "VALUES (:nozzle_id, :shift_id, :entry_date, :liters, :note, :user_id, :recorded_at)"
    )
    for row in sale_rows:
        bind.execute(
            insert_stmt,
            {
                "nozzle_id": row.nozzle_id,
                "shift_id": row.shift_id,
                "entry_date": row.entry_date,
                "liters": row.testing_liters,
                "note": "Migrated from meter reading",
                "user_id": row.user_id,
                "recorded_at": row.recorded_at,
            },
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nozzle_testing')
    # ### end Alembic commands ###
