"""date the tank starting-stock baseline

Revision ID: 7e1da14107b5
Revises: 58a72e023f1b
Create Date: 2026-08-04 12:07:58.208992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e1da14107b5'
down_revision = '58a72e023f1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tank', schema=None) as batch_op:
        batch_op.add_column(sa.Column('starting_stock_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tank', schema=None) as batch_op:
        batch_op.drop_column('starting_stock_date')

    # ### end Alembic commands ###
