"""testing transfers, dip water level, sales returns

Revision ID: 929a9a789530
Revises: 7e1da14107b5
Create Date: 2026-08-04 23:31:40.944864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '929a9a789530'
down_revision = '7e1da14107b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_return',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('fuel_type_id', sa.Integer(), nullable=False),
    sa.Column('tank_id', sa.Integer(), nullable=False),
    sa.Column('liters', sa.Float(), nullable=False),
    sa.Column('price_per_liter', sa.Float(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_account.id'], ),
    sa.ForeignKeyConstraint(['fuel_type_id'], ['fuel_type.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shift.id'], ),
    sa.ForeignKeyConstraint(['tank_id'], ['tank.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sale', schema=None) as batch_op:
        # server_default is required here (autogenerate omits it) - existing
        # rows on a populated table have no value for a nullable=False
        # column being added, so without a default the ALTER fails outright
        # on Postgres, and on SQLite's batch-rebuild every existing row's
        # testing_liters would come back NULL instead of the intended 0.
        # Left in place (not dropped in a follow-up migration) since 0 is
        # also the column's permanent application-level default for any
        # future row that omits it.
        batch_op.add_column(sa.Column('testing_liters', sa.Float(), nullable=False, server_default='0'))

    with op.batch_alter_table('tank_dip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('water_cm', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tank_dip', schema=None) as batch_op:
        batch_op.drop_column('water_cm')

    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_column('testing_liters')

    op.drop_table('sales_return')
    # ### end Alembic commands ###
