"""add price_overridden to sale and direct_sale

Revision ID: 9ba9e030090d
Revises: ce5d5c042855
Create Date: 2026-08-18 22:32:46.383976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ba9e030090d'
down_revision = 'ce5d5c042855'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default is required here (autogenerate omits it) - existing
    # rows on a populated table have no value for a nullable=False column
    # being added, so without a default the ALTER fails outright on
    # Postgres, and on SQLite's batch-rebuild every existing row's
    # price_overridden would come back NULL instead of the intended False.
    # Every pre-existing row is correctly False: nothing that already
    # exists was "deliberately overridden" by this new mechanism, so it
    # stays eligible for reprice_entries() exactly as before. Left in
    # place (not dropped in a follow-up migration), same as
    # testing_liters's server_default='0' in 929a9a789530.
    with op.batch_alter_table('direct_sale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_overridden', sa.Boolean(), nullable=False, server_default=sa.false()))

    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_overridden', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_column('price_overridden')

    with op.batch_alter_table('direct_sale', schema=None) as batch_op:
        batch_op.drop_column('price_overridden')

    # ### end Alembic commands ###
