"""other income entry

Revision ID: fe480775b5a0
Revises: 4ee56b5e942d
Create Date: 2026-08-17 20:34:37.372310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe480775b5a0'
down_revision = '4ee56b5e942d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('other_income',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.Column('pump_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_account.id'], ),
    sa.ForeignKeyConstraint(['pump_id'], ['pump.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('other_income', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_other_income_pump_id'), ['pump_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('other_income', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_other_income_pump_id'))

    op.drop_table('other_income')
    # ### end Alembic commands ###
